### ISSUE TITLE
(/teamrequest request) does not work

### ISSUE THREAD

**Issue by j03ri** [Eluinhost/UHC#63]
I don't know plugin stuff but ye...
How can I fix the issue?!
It says ingame (An internal error occured while arrempting to perform this command)

[15:17:01 INFO]: j03ri issued server command: /teamrequest request

org.bukkit.command.CommandException: Unhandled exception executing command 'teamrequest' in plugin UHC v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_65]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_65]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: gg.uhc.uhc.config.ConfigException$Missing: No configuration setting found for key 'commands.teamrequest'
        at gg.uhc.uhc.config.impl.SimpleConfig.findKey(SimpleConfig.java:124) ~[?:?]
        at gg.uhc.uhc.config.impl.SimpleConfig.find(SimpleConfig.java:147) ~[?:?]
        at gg.uhc.uhc.config.impl.SimpleConfig.find(SimpleConfig.java:151) ~[?:?]
        at gg.uhc.uhc.config.impl.SimpleConfig.find(SimpleConfig.java:159) ~[?:?]
        at gg.uhc.uhc.config.impl.SimpleConfig.find(SimpleConfig.java:164) ~[?:?]
        at gg.uhc.uhc.config.impl.SimpleConfig.getString(SimpleConfig.java:206) ~[?:?]
        at gg.uhc.uhc.messages.BaseMessageTemplates.getTemplate(BaseMessageTemplates.java:68) ~[?:?]
        at gg.uhc.uhc.messages.BaseMessageTemplates.evalTemplate(BaseMessageTemplates.java:77) ~[?:?]
        at gg.uhc.uhc.messages.SubsectionMessageTemplates.evalTemplate(SubsectionMessageTemplates.java:64) ~[?:?]
        at gg.uhc.uhc.messages.SubsectionMessageTemplates.evalTemplate(SubsectionMessageTemplates.java:64) ~[?:?]
        at gg.uhc.uhc.modules.team.requests.RequestManager.finalizeRequest(RequestManager.java:119) ~[?:?]
        at gg.uhc.uhc.modules.team.requests.RequestManager.cancelRequest(RequestManager.java:159) ~[?:?]
        at gg.uhc.uhc.modules.team.requests.RequestManager.addRequest(RequestManager.java:185) ~[?:?]
        at gg.uhc.uhc.modules.team.requests.TeamRequestCommand.runCommand(TeamRequestCommand.java:66) ~[?:?]
        at gg.uhc.uhc.flagcommands.commands.OptionCommand.onCommand(OptionCommand.java:75) ~[?:?]
        at gg.uhc.uhc.flagcommands.commands.SubcommandCommand.onCommand(SubcommandCommand.java:134) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        ... 15 more

**Comment by Eluinhost** [comment]
Check out the Known Bugs section on the release page https://github.com/Eluinhost/UHC/releases/tag/1.0.0 On that page is a fix for it. The fix should already be in the code for later commits but they havn't been included in a release yet, I've got to clear some time to finish the next version

**Comment by j03ri** [comment]
k tnx
